version: '3'
services:
  nginx:
    image: nginx:1.23.2
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
      - ./data:/data/:ro
      - static_volume:/opt/app/static
      - media_volume:/opt/app/media
    depends_on:
      - service
      - fastapi
      - auth_api
    ports:
      - "80:80"

  redis:
    image: redis:7.0.6-alpine
    restart: always
    command: redis-server

  db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    env_file:
      - ./app/example/.env
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_HOST_AUTH_METHOD: "trust"

  service:
    build: app
    image: django:4.0.4
    restart: always
    volumes:
      - static_volume:/opt/app/static
      - media_volume:/opt/app/media
    env_file:
      - ./app/example/.env
    depends_on:
      - db
      - elasticsearch

  fastapi:
    build: fastapi
    image: fastapi:0.88.0
    restart: always
    env_file:
      - ./fastapi/.env
    ports:
      - 8001:8001
    depends_on:
      - db
      - redis
      - elasticsearch
      - service
    command: "uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8001"

  elasticsearch:
    image: elasticsearch:7.9.1
    restart: always
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - /opt/elasticsearch/data
    ports:
      - "9200:9200"

  etl:
    build: postgres_to_es
    env_file:
      - ./app/example/.env
    depends_on:
      - service

  auth_db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - auth_postgres_volume:/var/lib/postgresql/data
    env_file:
      - ./auth_api/.env
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_HOST_AUTH_METHOD: "trust"

  auth_api:
    build: auth_api
    image: auth_api
    restart: always
    env_file:
      - ./auth_api/.env
    depends_on:
      - auth_db
      - redis

  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      
volumes:
  postgres_volume:
  auth_postgres_volume:
  static_volume:
  media_volume:

